[pull]
show_list_post_pull = false

[request_review]
verify_isolation = false

[integrate]
verify_isolation = true
prompt_for_reassurance = true
pull_after_integrate = false

[fetch]
show_upstream_patches_after_fetch = true
